spring:
  application:
    name: chat-server
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      # Redis服务器地址
      host: ${redis.host}
      # Redis服务器端口号
      port: ${redis.port}
      # 使用的数据库索引，默认是0
      database: 1
      # 连接超时时间
      timeout: 1800000
      # 设置密码
      password: ${redis.password}

knife4j:
  enable: true
  setting:
    language: zh_cn

springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.abin.chatserver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd hh:mm:ss.SSS}){faint}
              %clr(%-5level)
              %clr(${PID:- }){magenta}
              %clr([%t]){faint}
              %clr(%-40.40logger{39}){cyan}
              %clr(:) %msg%n)"
server:
  port: 9999
